import type { SystemStyleObject } from "@chakra-ui/react";

export const s = {
  card: {
    position: "relative",
    bg: "card",
    border: "3px solid black",
    boxShadow: "4px 4px 0px 0px black",
    p: 5,
    w: "min(380px, calc(100vw - 24px))",
    maxW: "calc(100vw - 24px)",
    display: "flex",
    flexDirection: "column",
    gap: 3,
  },
  closeBtn: {
    position: "absolute",
    top: 3,
    right: 3,
    w: 7,
    h: 7,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    bg: "canvas",
    border: "2px solid black",
    boxShadow: "2px 2px 0px 0px black",
    cursor: "pointer",
    fontSize: "0.75rem",
    fontWeight: "900",
    lineHeight: 1,
    _hover: { transform: "translate(-1px, -1px)", boxShadow: "3px 3px 0px 0px black" },
    _active: { transform: "translate(1px, 1px)", boxShadow: "none" },
    transition: "transform 0.1s ease, box-shadow 0.1s ease",
  },
  title: {
    fontSize: "sm",
    fontWeight: "900",
    textTransform: "uppercase",
    letterSpacing: "0.08em",
    lineHeight: 1.2,
    pr: 8,
  },
  divider: {
    borderBottom: "2px solid black",
    my: 1,
  },
  description: {
    fontSize: "sm",
    lineHeight: 1.6,
    color: "fg",
  },
  progressRow: {
    pt: 1,
    gap: 2,
    alignItems: "center",
  },
  progressText: {
    fontSize: "xs",
    fontWeight: "700",
    color: "mutedFg",
    letterSpacing: "0.05em",
    textTransform: "uppercase",
  },
  dotsRow: {
    gap: 1.5,
  },
  dot: {
    w: "8px",
    h: "8px",
    border: "2px solid black",
    flexShrink: 0,
  },
  dotActive: {
    bg: "secondary",
  },
  dotInactive: {
    bg: "canvas",
  },
  footer: {
    pt: 2,
    borderTop: "2px solid black",
    gap: 2,
    justifyContent: "flex-end",
    flexWrap: "wrap",
  },
  actionBtn: {
    padding: "8px 16px",
    fontSize: "14px",
    fontWeight: "bold",
    textTransform: "uppercase",
    letterSpacing: "0.05em",
    border: "3px solid black",
    boxShadow: "2px 2px 0px 0px black",
    cursor: "pointer",
    transition: "transform 0.1s ease, box-shadow 0.1s ease",
    _hover: { transform: "translate(-1px, -1px)", boxShadow: "3px 3px 0px 0px black" },
    _active: { transform: "translate(1px, 1px)", boxShadow: "none" },
  },
} satisfies Record<string, SystemStyleObject>;
